#!/bin/sh
set -eux

# copy janet recipe
mkdir -p /sc/superconfigure/janet
cp ./.github/cosmo/recipe.mk /sc/superconfigure/janet/BUILD.mk
echo 'include janet/BUILD.mk' >> /sc/superconfigure/custom.mk

# build janet with cosmopolitan libc
export SOURCE_DIR=$(realpath .)
cd /sc/superconfigure
make o/janet/built.fat
