#!/bin/sh
set -e

sudo apt-get update
sudo apt-get install -y ca-certificates libssl-dev\
    qemu-utils qemu-user-static\
    texinfo groff\
    cmake ninja-build bison zip\
    pkg-config build-essential autoconf re2c

# download cosmocc
cd /sc
wget https://github.com/jart/cosmopolitan/releases/download/4.0.2/cosmocc-4.0.2.zip
mkdir -p cosmocc
cd cosmocc
unzip ../cosmocc-4.0.2.zip

# register
cd /sc/cosmocc
sudo cp ./bin/ape-x86_64.elf /usr/bin/ape
sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
